tianocore/edk2-pytool-library

- edk2toollib/utility_functions.py
- edk2toollib/windows/capsule/cat_generator.py
This is unnecessary code as RunCmd strips it off and will add it if necessary.
Also update RunCmd function header to provide details for two additional parameters.
> Remove quoting of command in Inf2Cat before calling RunCmd

- edk2toollib/windows/capsule/cat_generator.py
- edk2toollib/windows/locate_tools.py
- edk2toollib/windows/locate_tools_test.py
- readme.md
For platforms that don't have VS2017 or newer installed the vswhere based solution for locating the WinSDK dir doesn't work.  This change adds support for a best effort to look in known default install directories for the WinSDK tools.   The prefered method is still to use VsWhere and the vsvars files but this can help on older platforms.
> Add best effort support for locating WinSDK tools

- edk2toollib/utility_functions.py
RunPythonScript just calls into RunCmd. RunCmd got new optional parameters, this will plumb them through so callers of RunPythonScript will have access to them.
> Adding logging_level and raise_exception_on_nonzero to RunPythonScript

- edk2toollib/utility_functions.py
- edk2toollib/utility_functions_test.py
an x was in front of raise_exception_on_nonzero, which caused an exception
> [Bug Fix] Fix typo in RunPythonScript parameters

- edk2toollib/utility_functions.py
On certain operating systems, the processor information is returned in lowercase (some return upper case). This goes to upper or lower as needed
Fixes #26
> Make sure to do a case insensitive check on processor info

- edk2toollib/uefi/edk2/parsers/base_parser.py
The base parser currently emits a lot of errors due to missing variables and now that we don't filter as heavily, they need to be lowered to a more sensible level.
> [Fix] trim down on errors emitted from base_parser

- edk2toollib/uefi/edk2/parsers/base_parser.py
- edk2toollib/uefi/edk2/parsers/base_parser_test.py
Previously, when replacing variables, we would replace it with 0. This causes problems when we have dependencies on defines.
Fixes #58
> [Bug] Fix for macro replacement

- edk2toollib/utility_functions.py
We shouldn't do logging in GetHostInfo as it can be called before logging is fully up and running.
> [Bug] don't do logging in GetHostInfo utility function

- edk2toollib/uefi/edk2/parsers/base_parser.py
Update the Base Parser to support a DSC file conditional
statement such as the following:
!if $(CRYPTO_SERVICES) IN "ALL NONE MIN_PEI MIN_DXE_MIN_SMM"
One of the arguments is a quoted string that needs to be
parsed as a single argument.
The IN operator tests for membership.  Update parser to support
upper a lower case forms of the IN operator and use the
python set() type to test for membership if the IN operator
is being evaluated.
#72 
Signed-off-by: Michael D Kinney <michael.d.kinney@intel.com>
> edk2toollib/base_parser: Fix IN operator and quoted arguments

- edk2toollib/log/string_handler.py
- edk2toollib/log/string_handler_test.py
Previously, we didn't correctly seek to the end in string handler, this was just never used. This also drops Python 2 support from this file, which we don't support
> [Bug] Fix to seek_end in StringHandler

- edk2toollib/uefi/edk2/parsers/dec_parser.py
Update DEC parser to support PCD declarations of a
structured PCD that includes statements between
braces {}.  The information between the braces {} is
skipped.
#70 
Signed-off-by: Michael D Kinney <michael.d.kinney@intel.com>
> edk2toollib/dec_parser: Add support for structured PCDs

- edk2toollib/windows/capsule/cat_generator.py
Inf2Cat generation in cat_generator was failing in geographies where localtime is ahead of UTC with "DriverVer set to a date in the future" error message. Since the rest of capsule generation uses local time, https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/inf2cat recommends using /uselocaltime flag to Inf2Cat to avoid this issue.
> Add /uselocaltime flag to Inf2Cat

- edk2toollib/uefi/edk2/parsers/dsc_parser.py
- edk2toollib/uefi/edk2/parsers/dsc_parser_test.py
When parsing a DSC, we should keep track of all the files that are included in a DSC.
> [DSC_PARSER] Keep track of all the paths that we find in a DSC

- edk2toollib/uefi/edk2/path_utilities.py
This routine creates a common way to identify edk2 infs that might contain the file requested.  This is critical for determining if a set of changes to files impacts a package/platform/build.
This routine is not exact as it does not validate the input file is actually listed in the INF.  If a more exact list is needed more evaluation will need to be done.
> Add common routine to find a list of module Infs given a file

- edk2toollib/uefi/edk2/parsers/dec_parser.py
- edk2toollib/uefi/edk2/parsers/dec_parser_test.py
The DEC parser will throw errors when parsing DEC's that contain things like 
`gAdvancedFeaturePkgTokenSpaceGuid.PcdSmbiosType0BiosInformation.Vendor|0x1`
> [BugFix] updated the parser to handle structured pcd declarations

- edk2toollib/utility_functions.py
- edk2toollib/utility_functions_test.py
Python 3.4+ includes support for real enums. 
This class is offered as a compatibility shim.
> Change Enum to Python 3

- edk2toollib/uefi/edk2/path_utilities.py
- edk2toollib/uefi/edk2/path_utilities_test.py
For scenarios where the full packages path list might include invalid paths due to an incomplete code tree allow the caller to set 'error_on_invalid_pp' parameter to false.  This will remove the packagespath entries that not valid and will not generate an error.
> Support error or warning configuration for Edk2Path object

- edk2toollib/utility_functions.py
Modify utility_functions reader() implementation to be more permissive in the face of unexpected encoding coming from utilities executed with RunCmd()
> Modify utility_functions reader() implementation to be more permissive

- edk2toollib/windows/capsule/inf_generator.py
- edk2toollib/windows/capsule/inf_generator_test.py
Add the ability to set the IntegrityFilename and populate the data in the produced INF file.
Also refactored the way some of the INF sections are produced to make it easier to dynamically
add entries to these sections.
> windows/capsule: Update InfGenerator with integrity file

- edk2toollib/windows/capsule/inf_generator_test.py
A new unittest in #130 compared a fixed value to a date, which worked when submitted for PR, but fails on every other day (until the UNIX epoch wraps). This update corrects that and updates the dynamic value.
> Resolve the unittest error in the initial 0.10.14 release

- .cspell.json
- edk2toollib/windows/capsule/inf_generator2.py
- edk2toollib/windows/capsule/inf_generator2_test.py
Add inf_generator2 which supports generating multi-node capsules (targeting more than one ESRT).  This permits building capsules that can target more than one ESRT node, which is useful in scenarios where e.g. system configuration may require a slightly modified payload for the same firmware. 
A sample output:
```
;
; CapsuleName
; 1.0.0.1
; Copyright (C) Microsoft Corporation. All rights Reserved.
;
[Version]
Signature="$WINDOWS NT$"
Class=Firmware
ClassGuid={f2e7dd72-6468-4e36-b6f1-6488f42c1b52}
Provider=%Provider%
DriverVer=01/01/2021,1.0.0.1
PnpLockdown=1
CatalogFile=CapsuleName.cat
[Manufacturer]
%MfgName%=Firmware,NTamd64
[Firmware.NTamd64]
%tag1Desc% = tag1_Install,UEFI\\RES_{34e094e9-4079-44cd-9450-3f2cb7824c97}
%tag2Desc% = …
```
> Add a new inf_generator2 module with support for generating multi-node capsules

- edk2toollib/uefi/edk2/parsers/fdf_parser.py
- edk2toollib/uefi/edk2/parsers/test/fdf_parser_test.py
`sectionValue` wasn't being used and it broke the parsing on sections that didn't have a `x = y` part of the section.
> Fix `SECTION GUIDED` parsing

- azure-pipelines/windows-test-pr-ci.yml
windows-2022 does not have WDK installed due to there not being an official release for windows 11. WDK is necessary to pass ci, so downgrading to windows-2019 until there is a proper WDK for windows-2022.
> Downgrade pipeline to windows-2019

- edk2toollib/uefi/edk2/parsers/buildreport_parser.py
The Build Report will line break after 120 characters which causes parser errors when Module INF Paths are longer than 101 characters. This change reads additional lines until the Module INF Path contains ".inf".
> Add long-line handling to build report parser for INF paths

- azure-pipelines/azure-pipelines-release.yml
azure-pipelines-release.yml fails due to windows-latest (windows-2022) VM not currently having a WDK. Due to this, release builds fail and is not distributed to PyPI. Downgrading to windows-2019 until windows-2022 includes WDK
> Downgrade azure-pipelines-release.yml vm to windows-2019

- edk2toollib/utility_functions.py
- license.txt
This is necessary to enable GNU make's job control to pass through
commands like stuart_build.  GNU make's job control is implemented using
tokens on file descriptor.  If the file descriptors remain open, a GNU
make calling stuart_build can communicate with a GNU make called by
stuart_build.  However, Python's Popen closes file descriptors by
default.
This change adds a close_fds argument to RunCmd, which passes through to
Popen.  It defaults to True, which is Popen's default value, so existing
behaviors are not changed.
A similar change will be proposed in edk2-pytool-extensions.
> Introduce close_fds argument in RunCmd

- edk2toollib/gitignore_parser.py
- edk2toollib/gitingore_parser_test.py
This PR fixes the following:
1. The benign bug for the path separator regex as referenced in #150. The possible separators previously included "|" as a possible delimeter; this has been removed.
2.  A deprecation warning regarding where flags must be located in a regex string. There used to be no requirement, however it is now required that flags are located at the front of the regex string. This changes anchored patterns from being `^(?ms)\<something>` to `(?ms)^\<something>`
3. provides a bugfix where negation rules were not working properly as mentioned in #175 
4. Add test coverage for gitignore_parser
> Multiple fixes to gitignore_parser.py

- edk2toollib/uefi/edk2/path_utilities_test.py
Add the ability handle path names where the package name shows up in the package path before the package path. As an example, would be` ClientPkg/CLIENT_PKG/ClientPkg/ClientPkg.dec`
> Add GetEdk2RelativePathFromAbsolutePath() unit test for poor path names

- edk2toollib/uefi/edk2/path_utilities.py
- edk2toollib/uefi/edk2/test_path_utilities.py
This series makes three main changes:
1. [Add test case to show bug in GetContainingModules()](https://github.com/tianocore/edk2-pytool-library/commit/6badaf4581bce1f53445e5899bcb481be0437e66)
Adds `test_get_containing_module_with_infs_in_other_temp_dirs()` to
path_utilities_test.py to show that `GetContainingModules()` will
extend its file search for a .inf file beyond the maximum parent of
its `Edk2Path` object instance.
This failure would already reproduce if the user happen to have a
.inf file in their temporary directory. This test case adds such a
file to always show this file is returned.
Further illustrates https://github.com/tianocore/edk2-pytool-library/issues/188
`GetContainingModules()` will be updated to prevent this behavior in
a future change.
2. [Verify paths in …
> Enhance Edk2Path.GetContainingModules() [Rebase & FF]

- edk2toollib/uefi/edk2/path_utilities.py
- edk2toollib/uefi/edk2/test_path_utilities.py
Adds an environment variable called `PYTOOL_TEMPORARILY_IGNORE_NESTED_EDK_PACKAGES`
that a platform can set to `"true"` to allow nested packages.
Nested packages are a violation of EDK II package rules and should
be fixed. This is provided for backward compatibility and temporary
use until the variable is no longer needed.
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
> Edk2Path: Add an env variable to allow nested packages

- edk2toollib/uefi/edk2/path_utilities.py
- edk2toollib/uefi/edk2/test_path_utilities.py
Closes #204
Updates `Edk2Path.GetContainingModules()` to preserve case the case
for each absolute path returned in the list of absolute paths.
This allows callers dependent on case comparison to get the expected
result.
Also adds a new test case used to verify this change:
- `test_get_containing_modules_path_format()`
Used to confirm the case in paths returned from
`Edk2Path.GetContainingModules()`
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
> path_utilities.py: Prevent path case modification in GetContainingModules()

- edk2toollib/uefi/edk2/test_path_utilities.py
Adds a test case to verify the function returns POSIX paths as expected.
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
> Add GetEdk2RelativePathFromAbsolutePath() POSIX test case

- .github/ISSUE_TEMPLATE/bug_report.yml
Lists the Python versions supported for bug fixes in the bug reporting form.
This is to make it obvious what Python versions are officially supported for bug fixes when a bug is filed.
Contributes to https://github.com/tianocore/edk2-pytool-library/issues/201
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
> bug_report.yml: Add supported Python versions

- docs/contributor/python_release.md
- setup.py
Adds a required minimum version of python during pypi release that is
mirrored on pypi.org so that it is obvious what python versions are
supported for edk2-pytool-library.
Additionally adds a new contributor doc file that specifies all files
that must be updated when a new minor version of python is released.
Signed-off-by: Joey Vagedes <joeyvagedes@microsoft.com>
> Add required python version for pypi

- edk2toollib/tests/test_path_utilities.py
- edk2toollib/uefi/edk2/path_utilities.py
This adds an environment variable to allow the nested package check to be demoted to an INFO-level log for packages that are known to be bad and cannot be immediately remediated. This avoids a large number of warning messages that would otherwise make it more likely for developers to ignore warnings entirely.
> Add support for ignoring known-bad packages

- setup.py
This updates the setup.py script used for installing edk2-pytool-extensions as a pypi module to only install vswhere if we are on a windows device.
Closes #235
> Only download vswhere if on windows

- edk2toollib/utility_functions.py
platform.uname() returns Darwin instead of MacOs due to backwards compatibility. Force GetHostInfo() to return MacOs rather than Darwin as darwin is the kernal, not the OS.
> utility_functions: Force GetHostInfo() to return MacOs

- edk2toollib/utility_functions.py
If locality information is missing on the system, `locale.getdefaultlocale()` fails to return a valid encoding and thus any `RunCmd()` call will fail. This adds in the logic to default to utf-8 if locality information returns None for the encoding.
> utility_functions.py - bugfix encoding when locale information missing

- edk2toollib/windows/locate_tools.py
This is a potential fix for _DownloadVsWhere attempting to download to a folder that doesn't exist and raises an exception that is never shown to the user. 
This fix will attempt to create the folder if it is determined that the folder does not exist - and raise an unhandled exception up for logging
> potential fix to broken vswhere

- edk2toollib/windows/locate_tools.py
Within `QueryVcVariables()`, A set comparison is made between the requested variables and the returned variables to determine (and raise an error printing) the missing keys. There is a difference in case for the two sets, one being all uppsercase values while the other is not. This change updates both sets to contain all uppercase values.
Reported by @LethargicHitman in #297
> locate_tools: set comparison invalid due to mismatched case of keys

- edk2toollib/uefi/edk2/path_utilities.py
Updates Edk2Path documentation to inform users that Edk2Path instantiation is an expensive operation due to packages path and package validation, so it should be instantiated as few times as possible. Requested via #288
> path_utilities.py: update Edk2Path documentation

- edk2toollib/windows/capsule/inf_generator.py
- edk2toollib/windows/capsule/inf_generator2.py
- tests.unit/test_inf_generator.py
- tests.unit/test_inf_generator2.py
The required DefaultDestDir was changed from `%DIRID_WINDOWS%,Firmware\{6bd4efb9-23cc-4b4a-ac37-016517413e9a}` to `13` with the release of Windows 10 1803 but was never updated in either inf_generator.py or inf_generator2.py. As Windows 10 1803 has been EOL since November 12, 2019,  I see no reason to support the previous requirements and will transition to the new value.
Thanks @joschock for bringing this to light in #291
> inf_generator: update DefaultDestDir

- .vscode/settings.json
Updating vscode settings to point to the correct location for pytests
> updating vscode settings to point to the unit tests

- .github/dependabot.yml
Updates the frequency of checks to once a week, mondays at 01:00 UTC.
It was noted that for any given release of edk2-pytool-library, that multiple dependencies were updated multiple times, which is a waste of maintainer time. This moves the checks to once a week at Monday, to be reviewed and merged every Monday morning.
> dependabot.yml: Update frequency of checks

- edk2toollib/uefi/authenticated_variables_structure_support.py
This fixes a bug in EDK2-Pytool-Extensions where a unit test was failing due to the attributes being renamed. Deprecation warnings have been added to allow for those unit tests to pass with warnings
> adding missing attributes

- edk2toollib/windows/capsule/inf_generator.py
- edk2toollib/windows/capsule/inf_generator2.py
- tests.unit/test_inf_generator2.py
[Pr #315 ](https://github.com/tianocore/edk2-pytool-library/pull/315) Introduced a bug with capsule update from the OS where the capsule update fails and shows up as _error: missing file %hs_.  This fixes that bug by correctly putting the FirmwareIntegrityFilename into the new directory with FirmwareFilename.
Fixes [Issue #351](https://github.com/tianocore/edk2-pytool-library/issues/351)
Tested on Intel physical platforms.
> Capsule install fix for the inf_generators.

- edk2toollib/uefi/edk2/parsers/dec_parser.py
- tests.unit/parsers/test_dec_parser.py
previously, the dec parser would fail to parse a PcdDeclarationEntry that contained a pipe symbol in the default value. This commit updates the parser to detect pipes wrapped in quotes and not split on it.
closes #234
> dec_parser: support parsing pcd strings with pipes

- edk2toollib/uefi/edk2/path_utilities.py
- tests.unit/test_path_utilities.py
Updates path_utilities to use pathlib rather than os.path functionality as it abstracts away posix vs windows path separators.
Continues to provides self.WorkspacePath and self.PackagePath as a string and list of strings respectively, but internally they are held as a pathlib.Path object and internal functionality uses it as such.
Resolves an issue where GetEdk2RelativePathFromAbsolutePath could return a Non-Posix path.
closes #207 
Also making initial updates in preparation for deprecating mws (multiple_workspace.py in edk2-pytool-extensions) found in https://github.com/tianocore/edk2-pytool-extensions/issues/446
> path_utilities: Use pathlib

- edk2toollib/log/ansi_handler.py
- tests.unit/test_ansi_handler.py
Previously, the ansi_handler only accepted strings in the logging record message due to a bug in how the message was retrieved from the record. This change fixes this, allowing any object that `str()` works on to be used as a message in the logging record.
This fix works by converting the message to a str (similar to `LogRecord.getMessage()`) then appending the color code. We cannot call `.getMessage()` directly as that will insert any args into the string, which causes a break later when `.getMessage()` is called again by the logging library (An exception is raised due to attempting to insert an argument into a string without a corresponding `%` placeholder).
closes #143
> ansi_handler: support all string representable objects in LogRecord message

- edk2toollib/uefi/edk2/parsers/base_parser.py
- edk2toollib/uefi/edk2/path_utilities.py
- tests.unit/test_path_utilities.py
`GetEdk2RelativePathFromAbsolutePath` and `GetAbsolutePathOnThisSystemFromEdk2RelativePath` now allow the caller to provide the path parts as individual arguments instead of needing to join them together manually. Continues to support a single joined path argument.
This is to support the deprecation of [MultipleWorkspace](https://github.com/tianocore/edk2-pytool-extensions/blob/master/edk2toolext/environment/multiple_workspace.py) in edk2-pytool-extensions per https://github.com/tianocore/edk2-pytool-extensions/issues/446. With this change, users can now substitute `MultipleWorkspace.join(...)` for `Edk2Path.GetAbsolutePathOnThisSystemFromEdk2RelativePath(...)`.
Tests now include verifying the same output for manually joined paths and paths provided by parts when calling …
> path_utilities: allow path parts to be passed

- edk2toollib/uefi/edk2/path_utilities.py
- tests.unit/test_path_utilities.py
This fixes a bug that was introduced in commit
85b899a8a29c839fca15f4b8a008e4654cc71697 that resulted in GetContainingPackage no longer supporting non-existent files. This commit fixes that bug and adds a unit test to ensure that it does not happen again.
> path_utilities: bugfix: GetContainingPackage support non-existent files

- edk2toollib/gitignore_parser.py
- tests.unit/parsers/test_gitingore_parser.py
- tests.unit/test_guid_list.py
Merges upstream changes of gitignore_parser.
The upstream changes were needed to add support for ignoring files with no extension via the following rule triple:
```txt
*     [Ignore all]
!*.*  [Un-ignore all files with extensions]
!*/   [Un-ignore all directories]
```
Puts us at [133bd62562622be096f495fbca7b37a1faac3ab7](https://github.com/mherrmann/gitignore_parser/commit/133bd62562622be096f495fbca7b37a1faac3ab7)
> gitignore_parser: merge upstream changes

- edk2toollib/database/tables/instanced_fv_table.py
- edk2toollib/database/tables/instanced_inf_table.py
- edk2toollib/database/tables/source_table.py
- tests.unit/database/test_instanced_fv_table.py
- tests.unit/database/test_instanced_inf_table.py
Removes autoincrementing primary keys from `instanced_fv`, `instanced_inf` and `source` tables. Tables depending on an autoincremented index as a foreign key end up breaking when doing a naive merge of two databases as the index is automatically updated in the table where it is the primary key, but it is not updated in the table where it is a foreign key, thus breaking the association.
To support merging two databases where we will never know the true tables in the database (A developer can register a subset of provided tables or create their own), core tables should not use autoincremented primary keys.
This removal was simple as there was no existing dependencies that utilized the auto-incremented primary key. Getting the same association can be done via combining the `env` and …
> edk2toollib/database: remove autoincrement id

- edk2toollib/database/edk2_db.py
- edk2toollib/database/tables/instanced_inf_table.py
Most queries rely on a specific env value when generating results; this commit adds an index on the env column for the junction table as it can get extremely large and index's here will improve performance when filtering on a specific env value.
> edk2toollib.database.edk2_db: Add env index to large tables

- edk2toollib/uefi/edk2/parsers/base_parser.py
- edk2toollib/uefi/edk2/parsers/dsc_parser.py
- tests.unit/parsers/test_base_parser.py
- tests.unit/parsers/test_dsc_parser.py
Improves the following parsers in the following ways:
`base_parser.py`: Properly uses ivalue (int value) to check if the string representation of a value was correctly converted to an integer ('1' to 1, '0x0' to 0, etc) when evaluating conditionals
`dsc_parser.py`: register pcds when performing the initial parse responsible for finding define statements. This is necessary to evaluate conditionals that use pcds.
> edk2toollib/uefi/edk2/parsers: enhancements

- edk2toollib/uefi/edk2/parsers/base_parser.py
- tests.unit/parsers/test_base_parser.py
recent changes to conditional evaluations to support evaluating non decimal integers such as hex strings broke the ability to evaulate define macro replacements that are integers. This is a bugfix to keep that support along with additional tests to ensure it does not break in the future.
> base_parser.py: conditional evaluation bugfix

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/VariableProducer.yml
- docs/contributor/python_release.md
- pyproject.toml
- readme.md
Updates all documentation and testing to use python 3.10, 3.11, and 3.12. 
Additionally adds a python-requires section to the pyproject.toml, to ensure a proper error if someone tries to pip install edk2-pytool-library v0.19.0 on a python version less than 3.10
> Update Supported Python versions to 3.10, 3.11, and 3.12

- edk2toollib/windows/capsule/inf_generator.py
- edk2toollib/windows/capsule/inf_generator2.py
- tests.unit/test_inf_generator.py
- tests.unit/test_inf_generator2.py
The inf generators generate capsules with:
```inf
[DestinationDirs]
DefaultDestDir = 13
```
The syntax 'DIRID 13' was introduced in OS version 10.0.16299, but DDInstall sections utilizing the syntax will install on earlier OS versions. Those DDInstall sections should be restricted to only install on 10.0.16299 or higher using a TargetOSVersion decoration.
See [Combining platform extensions with operating system versions](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/combining-platform-extensions-with-operating-system-versions)
Tested before and after with `infverif.exe`
> Limiting capsule install to supported versions

- edk2toollib/uefi/edk2/path_utilities.py
- tests.unit/test_path_utilities.py
Removes Nested package exceptions from path_utilities.py in favor of a warning.  This is being done as the exception has served its purpose and those willing to update their nested packages have had a year to do so. Any nested packages will now only be a warning logged at logging.DEBUG and issues with converting from an absolute path to an edk2 package path relative path will be accepted.
A new CI Check has been added so that packages managed by that specific repository will still be checked by nested packages, but nested packages outside of the control of that specific repository will not be checked and thus not result in an exception being raised.
closes #200
> path_utilities: Remove Nested package exceptions

- edk2toollib/gitignore_parser.py
- tests.unit/parsers/test_gitingore_parser.py
This squash commit merges in changes from mherrmann/gitignore_parser for the following commits:
7956d03: remove unused variable whitespace_re
ffbfd79: remove regex flags m, s
d45a085: Fix pattern with slash in range
1040aa5: Fix pattern with leading exclamation marks
cdf80b7: Fix lack of implicit anchoring of patterns to direcotry separators
cdf80b7: Fix multi-astericks that fall outside of the special cases
6abc776: Fix "a/**/b" matching "a/bb"
721f804: do not resolve symlinks
This is specifically necessary for **721f804: do not resolve symlinks** which was causing the GuidCheck plugin to fail for Edk2 as it has a symbolic link: https://github.com/tianocore/edk2/blob/master/EmulatorPkg/Unix/Host/X11IncludeHack
> gitignore_parser.py: Multiple Updates

- edk2toollib/uefi/edk2/path_utilities.py
In a less used conditional case, self.Logger was referenced, whereas in the rest of the file self.logger is used. Resulted in an exception.
File "Lib\site-packages\edk2toollib\uefi\edk2\path_utilities.py", line 111, in __init__
self.Logger.log(logging.WARNING, warning)
^^^^^^^^^^^
AttributeError: 'Edk2Path' object has no attribute 'Logger'. Did you mean: 'logger'?
> Corrected Logger case to logger in error condition

- edk2toollib/utility_functions.py
- tests.unit/test_utility_functions.py
On Windows systems with long paths disabled, the RemoveTree function fails to remove files that go over the character limit as they cannot be found. This change, on windows, prefixes the path with the '\\\\?\\' which allows for the detection of long paths, and allows for the removal of the file.
Closes #445
> utility_functions: Add LongPath support to RemoveTree

- edk2toollib/database/tables/inf_table.py
- edk2toollib/database/tables/instanced_inf_table.py
- edk2toollib/database/tables/package_table.py
- edk2toollib/uefi/edk2/parsers/dsc_parser.py
- edk2toollib/uefi/edk2/parsers/inf_parser.py
- tests.unit/database/common.py
- tests.unit/database/test_inf_table.py
- tests.unit/database/test_instanced_inf_table.py
- tests.unit/database/test_package_table.py
- tests.unit/parsers/test_inf_parser.py
Contains multiple commits to improve `instanced_table`, `instanced_inf_table`, and `dsc_parser`.
Updates inf_table.py to resolve dot-dot paths in source files before inserting it into the database to ensure the path is a valid edk2 package path relative path. Source files in the database are now edk2 package relative rather than inf relative.
The dsc_parser is architecture agnostic and resolves the dsc file for all architectures it supports. This means the instanced_inf_table must filter the results to only the architectures specified by the Settings file.
The dsc_parser relied on TARGET_ARCH when creating scoped libraries and components, but it should rely on SUPPORTED_ARCHITECTURES which provides information true to the DSC.
Adds additional parsing to the inf_parser to support scoped …
> [REBASE&FF] Multiple table / parser updates

- edk2toollib/uefi/edk2/parsers/base_parser.py
- tests.unit/parsers/test_hash_file_parser.py
Edk2 supports pound signs in pcd definitions, however the simple edk2 config file parser provided by edk2-pytool-library did not support this. This commit updates the removal of comments to only remove pound signs (and everything after) if the pound sign is not wrapped in quotes.
> base_parser: Don't treat pound signs wrapped in quotes as comments

- edk2toollib/uefi/edk2/parsers/base_parser.py
- tests.unit/parsers/test_hash_file_parser.py
Previous update to StripComment would ignore any pound signs that were surrounded by quotes, but did not consider if the sign was inside two quotes or between two sets of two quotes (i.e. `" # "` vs `" 1 " # " 2 "`). This commit updates StripComment to check this scenario and not strip if the pound sign is inside two quotes.
This additionally adds support for ignoring escaped quotes.
> base_parser: Update StripComment to consider quote groupings

- edk2toollib/uefi/edk2/parsers/buildreport_parser.py
Updates the buildreport parser to also parse the depex section instead of skipping it.
> buildreport_parser: Add Depex section parsing

- edk2toollib/database/tables/instanced_fv_table.py
- edk2toollib/database/tables/instanced_inf_table.py
- tests.unit/database/test_instanced_fv_table.py
- tests.unit/database/test_instanced_inf_table.py
INF paths in the DSC and FDF can be defined as an absolute path, relative to the workspace, or relative to any package path. To ensure consistency with paths, this change converts any provided path to be relative to the closest package path. This simplifies queries that typically use the `path` column for filtering, or `join` commands.
That is to say, if there are two package paths: `Common/`, `Common/Special/`, a path can be relative to either of these packages paths. So both `Special/Files/MyFile.c` and `Files/MyFile.c` are acceptable. However when inserting into the database, we now ensure that the closest package path relative path is used. In the above example, that means `Files/MyFile.c`.
> table parsers: Use closest package path relative path

- .vscode/settings.json
- edk2toollib/windows/locate_tools.py
Adds a new function, FindAllWithVsWhere which functions the same as FindWithVsWhere, but returns a list of all paths found, rather than the first path only.
Updates QueryVcVariables to use FindAllWithVsWhere, and loops through each path found, attempting to locate the vcvarsall.bat file. It will use the first one found; if none are found, it will print an error and raise an exception.
Installed multiple instances of VS tools and verified FindAllWithVsWhere produces paths for both. Removed vcvarsall.bat from one installation and verified that it was found in the second installation. Then removed vcvarsall.bat from both installations and verified the error message printed as expected.
Closes #486
> locate_tools: Search all VS installations for vcvarsall.bat

- docs/user/features/.pages
- docs/user/gen_api.py
- docs/user/index.md
- edk2toollib/database/edk2_db.py
- mkdocs.yml
Associated with #392, but will not close until also completed in edk2-pytool-extensions.
- Changes the theme to material instead of readthedocs as there are no longer any plans to post this to readthedocs.
- Utilizes new features in mkdocs-awesome-pages to allow for a hierarchical sidebar for the API references rather than a flattened list of API references.
- Adds light / dark mode to the docs
- Adds navigation tabs in the header for the main links.
> mkdocs: General DocSite improvements.

- edk2toollib/utility_functions.py
the reader() function, used to parse the output of a subprocess would decode using a different standard as specified by
locale.getdefaultlocale(), which was deprecated. This commit changes the decode format to be sys.stdout.encoding, which is more accurate than locale.getdefaultlocale() as it is the actual encoding of stdout, which is what the reader function is decoding
Cannot tag @kuqin12, so doing it here.
closes #216
> utility_functions: reader: use stdout encoding

- .github/workflows/doc-release.yml
Updates deploy-pages github action to 4.0.1 which, from deploy-pages should resolve the build error being seen is [ #732 ](https://github.com/tianocore/edk2-pytool-extensions/issues/732)
> Update deploy-pages to 4.0.1

- .cspell.json
- edk2toollib/database/tables/source_table.py
- pyproject.toml
- tests.unit/database/test_source_table.py
Add a keyword argument to `SourceTable` that allows for source analysis (# of LOC, # of Comments, # of empty lines) to be analyzed per source file. Disabled by default as it greatly increases the parse time.
> source_table: Add optional source analysis.

- edk2toollib/database/tables/instanced_inf_table.py
- tests.unit/database/test_instanced_inf_table.py
Adds all NULL libraries that are defined in a library classes section, to the list of libraries associated with a specific component.
ensures all NULL libraries are only associated with the component, and not libraries of that component.
> instanced_inf_table: include NULL libs

- .github/workflows/CIRunner.yml
- readme.md
Upgrades markdownlint-cli to 0.39.0 from 0.32.2.
The release is currently failing as the release pipeline that comes from edk2-pytool-extensions does not have a locked version of markdown lint. This upgrades markdownlint-cli to 0.39.0, which will be the locked version in edk2-pytool-extensions.
> upgrade markdownlint-cli

- edk2toollib/uefi/edk2/parsers/base_parser.py
- tests.unit/parsers/test_base_parser.py
add ability to parse a condition expression without spaces between the argument and the condition, so long as the condition starts with a [!, >, <, =]. This is to bring parody with the edk2 build system, which supports parsing this.
Examples now supported:
!if $(var)==TRUE
!if $(var) ==TRUE
!if $(var)== TRUE
> base_parser: support no spaces in conditional expression

- edk2toollib/uefi/edk2/parsers/buildreport_parser.py
A path from an ext dep used for an INF will be absolute. This causes the build report parser to fail to match that path to a component since the check is performed against a relative path.
This change checks if a path is absolute before the comparison. If so, the path is converted to a package path adjusted path for the comparison.
> buildreport_parser: Support component INF absolute paths

- edk2toollib/windows/capsule/inf_generator.py
- edk2toollib/windows/capsule/inf_generator2.py
- tests.unit/test_inf_generator.py
- tests.unit/test_inf_generator2.py
Limit capsule install inf changes to OS versions 17134 or higher for a newer HDC requirement.
Original PR - https://github.com/tianocore/edk2-pytool-library/pull/431
"According to Zac Lockard for the InfVerif team, the new WHCP requirements went into force with the newest 26080 build which is why we're seeing this now. For reference, they link https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/inf-validation-errors-and-warnings#1199 and quote the page that says "You must fix all errors in order to pass driver tests in Hardware Dev Center."
It is the Device.DevFund.INF.Syntax requirement
This change was also pushed to all older versions of the OS due to this being a problem often in the ecosystem".
> Update OS version to 17134 to limit DDInstall sections

- edk2toollib/windows/locate_tools.py
`pkg_resources` module included with setuptools has been depreciated and now removed in python 3.12, resulting in import errors when using locate_tools functionality on 3.12. This change resolves the issue by using `importlib.resources` in it's place.
> remove usage of `pkg_resources`

- .cspell.json
- edk2toollib/os/__init__.py
- edk2toollib/os/uefivariablesupport.py
- pyproject.toml
Adding a common Uefi Variable Access class for both windows and linux.
Class UefiVariable supports:
GetUefiVar - Get a single Uefi Variable's data
GetUefiAllVarNames - Get all Uefi variables
SetUefiVar - Set (or delete) a single Uefi variable.
Multiple copies of this class are floating in repos, mainly to support tools. This is to consolidate support.
Verified DecodeUefiLog is able to use this instance to retrieve log on a physical system.
> Adding Uefi Variable Support.

- edk2toollib/os/uefivariablesupport.py
GetUefiVariable originally returned a buffer which was larger than the variable size. 
This was modified to only return the buffer of the variable size, but the modification caused an exception (variable not initialized).
Modifying the code again to initialize the variable, and to retrieve the correct variable size.
> Address Linux GetUefiVariable exception. 

- edk2toollib/uefi/edk2/parsers/dec_parser.py
- tests.unit/parsers/test_dec_parser.py
The PCD parsing regex pattern failed for PCDs that had a single quote
For example, 
gEfiMdePkgTokenSpaceGuid.PcdSingleQuote|"eng'fraengfra"|VOID*|0x0000002f
CRITICAL - EXCEPTION: Too few parts: ['PcdSingleQuote|"eng\'fraengfra"', 'VOID*', '0x0000002f']
The new pattern should allow the usage of single quotes
> Fix PCD parsing for PCDs that have a single quote in them

- docs/user/features/edk2_db.md
- mkdocs.yml
[MkDocs v1.5.0](https://github.com/mkdocs/mkdocs/releases/1.5.0) Updated how links were evaluated (See "Expanded Validaton of links" section). Before 1.5.0, most links in our documentation were left "untouched" as they either started or ended with a `/`.
> ... links that started with `/` ("absolute") and links that _ended_ with `/` were left as is ...
However these links are now properly evaluated, which broke most links in edk2-pytool-extensions documentation. With this new evaluation, All of our links that started absolute (`/`) were now linking relative to `tianocore.org` instead of `tianocore.org/edk2-pytool-library`.
This pull request updates the documentation to utilize the newly introduced `absolute_links` validation setting to be `relative_to_docs` which updates absolute paths to …
> Documentation: Fix all broken links

- docs/contributor/developing.md
Update formatting to use ruff and provide some background info
about how the pip modules are installed.
> docs/developing.md: Update outdated steps

- tests.unit/test_locate_tools.py
Currently, this function depends on finding the actual inf2cat.exe tool which is dependent on the user's system. Instead mock the dependencies so the function logic is excercised but with consistent dependency values.
> test_locate_tools: Make test_FindInf2CatToolInWinSdk() results consistent

- edk2toollib/gitignore_parser.py
- tests.unit/parsers/test_gitingore_parser.py
In IgnoreRule.match(), simply return False if the given absolute path is not a subpath of the base path instead of not handling the exception and breaking the overall build.
> gitignore_parser.py: Handle non-subpaths in rule file check

- .github/workflows/CIRunner.yml
- docs/contributor/developing.md
- tests.unit/parsers/test_gitingore_parser.py
Update the pipelines and documentation to specify that `ruff check` and `ruff format` should be (and will be in the pipelines) run on the workspace
> [REBASE&FF] Run ruff check and ruff format on the workspace

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/VariableProducer.yml
- pyproject.toml
- readme.md
This commit removes support for python 3.10. Attempting to install v0.22.0 of edk2-pytool-library using a python version less than 3.11 will result in an error from pip along the lines of `ERROR: Could not find a version that satisfies the requirement ...`
If your platform cannot upgrade to 3.11 or above, continue using a version of edk2-python-library less than v0.22.0. Otherwise upgrade your version of platform to 3.11 or greater.
> Python support: drop 3.10, add 3.13

- edk2toollib/uefi/edk2/parsers/fdf_parser.py
- tests.unit/parsers/test_fdf_parser.py
Previously, the FDF parser would fail to parse an FDF file with statements containing a SECTION COMPRESS with additional with nested sub sections. 
Below is an example of a statement the parser failed to parser:
```
FILE RAW = <guid> {
SECTION COMPRESS {
SECTION RAW = $(OUTPUT_DIRECTORY)/$(TARGET)_$(TOOL_CHAIN_TAG)/FV/8C3D856A-9BE6-468E-850A-24F7A8D38E08.bin
}
}
```
This PR updates the parser to be able to get past the parsing of the this, by checking there is an equal in the statement line, and pass it.
> fdf_parser.py: support `SECTION COMPRESS` sections

- edk2toollib/uefi/edk2/parsers/base_parser.py
- tests.unit/parsers/test_dsc_parser.py
base_parser.py did not support conditional directives that were comparing to empty strings (e.g. `!if $(MY_VAL) == ""`, `!if $(MY_VAL) != "". The logic in `_TokenizeConditional`, was setting `mode` to QUOTE_MODE twice because the token length was zero for an empty quote (`len(token) == 0`).
This PR Updates the logic to not enter QUOTE_MODE when its already in QUOTE_MODE, and to fall over to end of QUOTE_MODE.
> base_parser.py: support conditions checking for empty string

- edk2toollib/os/uefivariablesupport.py
The UEFI variable fetching on Linux was broken, it was reading the attributes as part of the data, not correctly skipping over the attributes and fetching the data. For Linux, the value read is a UINT32 Attributes + Variable Length Data.
This change has been tested to fix that but reading (and current ignoring but logging an error if the attributes aren't 7, as ConfigEditor expects) the attributes and then fetching the data past that.
> Fix UEFI Variable Fetching on Linux

- edk2toollib/uefi/edk2/path_utilities.py
For GetEdk2RelativePathFromAbsolutePath change the type hinting of abspath from Tuple of strings to just str.
For GetAbsolutePathOnThisSystemFromEdk2RelativePath change the type hinting of relpath from Tuple of strings to just str.
This fixes the error messages from Pylint and Ruff about incompatible input types when using the functions as suggested. When attempting to pass a Tuple of strings to the functions, the functions would raise an error.
```
File "...\site-packages\edk2toollib\uefi\edk2\path_utilities.py", line 224, in GetAbsolutePathOnThisSystemFromEdk2RelativePath
relpath = Path(*[part.replace("\\", "/") for part in relpath])
^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'replace'
```
> Update GetEdk2RelativePathFromAbsolutePath and GetAbsolutePathOnThisSystemFromEdk2RelativePath path input type hinting

- edk2toollib/uefi/edk2/parsers/buildreport_parser.py
Currently, buildreport_parser maintains a dictionary of library classes.
This fails for NULL libraries. If more than one NULL library exists, only the last instance encountered will be in the dictionary.
To match edk2 build tool behavior, NULL libraries will have an instance number appened to the name.
i.e. NULL0, NULL1, etc
> buildreport_parser.py: Properly handle NULL libraries

- edk2toollib/log/file_handler.py
- edk2toollib/log/junit_report_format.py
With the addition of characters that require unicode support to source files, it is necessary to a default encoding of `utf-8` to prevent errors such as `UnicodeEncodeError: 'charmap' codec can't encode character '\u017f' when parsing file names.`
Encountered when attempting to work with SecurityPkg in edk2-stable202411 and the addition of complex copyright names.
> Set default stream encoding to utf-8 to `logging` handlers

- edk2toollib/uefi/edk2/path_utilities.py
- tests.unit/test_path_utilities.py
**test_path_utilities: Remove debug message count assumption**
Test that a nested package is found by the strings in the debug
message as opposed to the number of messages to avoid the test
being broken when unrelated debug messages are added.
---
**path_utilities: Optimize `Edk2Path` constructor**
`Edk2Path` objects are created relatively frequently throughout a
complete build process. This reduces the average execution time
in a full workspace by approximately half by using `os.walk()`
which is several seconds faster in the workspace and parallelizing
across package paths.
> Optimize `Edk2Path` [Rebase & FF]

- .cspell.json
- edk2toollib/windows/locate_tools.py
- tests.unit/test_locate_tools.py
Allows a caller to specify the exact compiler version to use for querying variables. This is useful because a system may have a single installation of (example) VS2022, but may have multiple versions of the VS2022 compiler installed. Prior to this change, QueryVcVariables would return variables arbitrarily based off of one of the installed compilers.
This change allows the caller to specify the exact version of the compiler to use for querying variables, so that the returned variables are consistent.
This allows for a bug regarding [WindowsVsToolChain](https://github.com/microsoft/mu_basecore/blob/dev/202405/BaseTools/Plugin/WindowsVsToolChain/WindowsVsToolChain.py) to be fixed as specified in: https://github.com/microsoft/mu_basecore/issues/1308
> locate_tools: QueryVcVariables: Allow exact vc

- pyproject.toml
Relax pywin dependency to be greater or equal to minimum version.
> Relax pywin dependency to be greater or equal instead of exactly equal

- edk2toollib/uefi/edk2/path_utilities.py
- tests.unit/test_path_utilities.py
Remove the sorted action for candidate_package_path_list to align with original build behavior.
> Remove the sorted action for candidate_package_path_list

- edk2toollib/uefi/authenticated_variables_structure_support.py
- tests.unit/test_authenticated_variables_structure_support.py
This pull request introduces several updates to the `EfiTime` class in `edk2toollib/uefi/authenticated_variables_structure_support.py` to improve code readability, add new functionality, and enhance test coverage. The changes include renaming internal attributes for consistency, adding new methods for binary data handling, and updating logging and testing.
* Renamed `_StructFormat` and `_StructSize` to `_struct_format` and `_struct_size` for consistency with Python naming conventions. 
* Added a `from_binary` class method to create an `EfiTime` instance from a byte representation.
* Introduced a `get_datetime` method to retrieve the `datetime` object from an `EfiTime` instance.
* Updated logging statements in the `decode` method to use f-strings for improved readability and consistency. …
> Updating EfiTime to decode bytes

- edk2toollib/uefi/authenticated_variables_structure_support.py
This pull request includes a minor change to the `print` method in `edk2toollib/uefi/authenticated_variables_structure_support.py`. The change ensures that the `sig_list_payload` object's `print` method is called with the `outfs` argument, aligning it with the method's signature.
> Fixing print statement

- edk2toollib/windows/capsule/inf_generator2.py
- tests.unit/test_inf_generator2.py
Today the targeted OS version is fixed to `10.0...17134`. Firmware may need to specify a minimum OS version that supports functionality in the firmware. This change allows a `InfHeader` to be created targeting a specific OS version or greater.
https://learn.microsoft.com/windows-hardware/drivers/install/combining-platform-extensions-with-operating-system-versions#targetosversion-decoration-format
> inf_generator2: Add TargetOSVersion option

- edk2toollib/windows/capsule/inf_generator2.py
- tests.unit/test_inf_generator2.py
The `DIRID_WINDOWS` is unused and removed.
> inf_generator2: Remove DIRID_WINDOWS from generated INFs
